# Used for local testing with Keycloak
FROM node:24-slim

# Allow node modules to be called directly
ENV PATH=$PATH:/client/node_modules/.bin

# Build client
WORKDIR /client
COPY package*.json ./
RUN npm set progress=false && npm ci --no-cache

# Run client
EXPOSE 4000
CMD [ "npm", "run", "start" ]