# Used for local development
FROM node:20-slim

# Allow node modules to be called directly
ENV PATH=$PATH:/client/node_modules/.bin

# Configure client container
WORKDIR /client

EXPOSE 4000

CMD [ "npm", "run", "start" ]
