FROM public.ecr.aws/bitnami/node:18.15.0

# Allow node modules to be called directly
ENV PATH $PATH:/client/node_modules/.bin

# Build client
WORKDIR /client
COPY package*.json ./
RUN npm set progress=false && npm ci --no-cache

# Run dev client
EXPOSE 4000
CMD [ "npm", "run", "start" ]