FROM public.ecr.aws/bitnami/node:18.15.0

# Allow node modules to be called directly
ENV PATH $PATH:/client/node_modules/.bin

# Configure client container
WORKDIR /client

EXPOSE 4000

CMD [ "npm", "run", "start" ]
