version: "3.7"

services:
  client:
    image: ${APP_NAME}-client
    container_name: ${APP_NAME}-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
    - 4000:4000
    volumes:
    - ./client:/client # Use client dir in host for hot reloading
    - /client/node_modules # Use node_modules in container
    depends_on:
    - server
    networks:
    - network

  server:
    image: ${APP_NAME}-server
    container_name: ${APP_NAME}-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
      args:
        VERSION: ${COMMIT_SHA}
    environment:
    - MONGODB_DATABASE=${MONGODB_DATABASE}
    - MONGODB_URI=${MONGODB_URI}
    - VERSION=${COMMIT_SHA}
    ports:
    - "8080:8080"
    - "9229:9229"
    volumes:
    - ./server:/server # Use server dir in host for hot reloading
    - /server/node_modules # Use node_modules in container
    depends_on:
    - mongodb
    networks:
    - network

  mongodb:
    container_name: ${APP_NAME}-mongodb
    image: mongo:3.6-xenial
    restart: always
    expose:
    - "27017"
    ports:
    - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    - MONGO_INITDB_PORT=27017
    volumes:
    - ./.docker/mongo/databaseInit:/docker-entrypoint-initdb.d
    - mongo-data-configdb:/data/configdb
    - mongo-data-db:/data/db
    networks:
    - network

networks:
  network:
    name: ${APP_NAME}-network
    driver: bridge

volumes:
  mongo-data-configdb:
    name: ${APP_NAME}-mongo-data-configdb
  mongo-data-db:
    name: ${APP_NAME}-mongo-data-db
