version: '2.4' # Depending on service condition was removed in v3+

services:
  client:
    extends:
      file: docker-compose.test.yml
      service: client

  server:
    extends:
      file: docker-compose.test.yml
      service: server
    command: npm run debug
    expose:
      - '8081'
      - '9229'
    ports:
      - '8081:8081'
      - '127.0.0.1:9229:9229'

  postgres:
    extends:
      file: docker-compose.test.yml
      service: postgres

  keycloak:
    extends:
      file: docker-compose.test.yml
      service: keycloak

networks:
  backend:
    driver: 'bridge'
