FROM public.ecr.aws/bitnami/node:14.17.3

# Allow node modules to be called directly
ENV PATH $PATH:/usr/src/app/node_modules/.bin

# Configure server container
WORKDIR /server

EXPOSE 4000

# Static env vars
ARG VERSION
ENV VERSION $VERSION

CMD [ "npm", "run", "watch" ]
