# Used for local testing with Keycloak, it includes hot reloading and uses ts-node for direct TypeScript execution
FROM node:20-slim

# Allow node modules to be called directly
ENV PATH=$PATH:/usr/src/app/node_modules/.bin

# Configure server
WORKDIR /server
COPY package*.json ./
RUN npm set progress=false && npm ci --no-cache

# Static env vars
ARG VERSION
ENV VERSION=$VERSION

# Development mode - uses hot reloading
CMD [ "npm", "run", "watch" ]