# This Dockerfile is optimized for local development, it includes hot reloading and uses ts-node for direct TypeScript execution
FROM public.ecr.aws/bitnami/node:18.15.0

# Allow node modules to be called directly
ENV PATH $PATH:/usr/src/app/node_modules/.bin

# Configure server container
WORKDIR /server

EXPOSE 4000

# Static env vars
ARG VERSION
ENV VERSION $VERSION

# Development mode - uses hot reloading
CMD [ "npm", "run", "watch" ]
