kind: Template
apiVersion: v1
labels:
  app: ${APP_NAME}
parameters:
- name: NAMESPACE
  description: The OpenShift namespace in which to deploy the server
  required: true
- name: APP_NAME
  description: App name that OpenShift objects will be prefixed with
  required: true
- name: IMAGE_REGISTRY
  description: Image registry from which to pull the image run by the job
  value: docker-registry.default.svc:5000
  required: true
objects:
- kind: Job
  apiVersion: batch/v1
  metadata:
    name: ${APP_NAME}-docdb-test-job
  spec:
    parallelism: 1
    completions: 1
    activeDeadlineSeconds: 1800
    backoffLimit: 6
    template:
      spec:
        containers:
        - env:
          - name: AWS_SSH_USERNAME
            valueFrom:
              secretKeyRef:
                key: AWS_SSH_USERNAME
                name: ets-aws-documentdb
          - name: AWS_SSH_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_SSH_KEY
                name: ets-aws-documentdb
          - name: AWS_SSH_HOST
            valueFrom:
              secretKeyRef:
                key: AWS_SSH_HOST
                name: ets-aws-documentdb
          - name: DB_SERVER
            valueFrom:
              secretKeyRef:
                key: DB_SERVER
                name: ets-aws-documentdb
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                key: DB_PORT
                name: ets-aws-documentdb
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: DB_USER
                name: ets-aws-documentdb
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DB_PASSWORD
                name: ets-aws-documentdb
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                key: DB_NAME
                name: ets-aws-documentdb
          name: ${APP_NAME}-docdb-test-job
          image: ${IMAGE_REGISTRY}/${NAMESPACE}/${APP_NAME}-server
          command: [/bin/ash, -c, "cd job && node docdb-test.js"]
        restartPolicy: OnFailure
