kind: Template
apiVersion: v1
metadata:
  name: mongodb-backup-template
parameters:
  - name: APP_NAME
    description: App name
    required: true
  - name: BACKUP_NAME
    description: Backup identifier
    value: pre-upgrade
    required: true
objects:
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-mongo-backup-${BACKUP_NAME}
      labels:
        app: ${APP_NAME}
        backup-name: ${BACKUP_NAME}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: netapp-file-standard

  - kind: Job
    apiVersion: batch/v1
    metadata:
      name: ${APP_NAME}-mongo-backup-${BACKUP_NAME}
      labels:
        app: ${APP_NAME}
        backup-name: ${BACKUP_NAME}
    spec:
      template:
        spec:
          containers:
            - name: mongodb-backup
              image: registry.hub.docker.com/centos/mongodb-36-centos7
              command:
                - /bin/bash
                - -c
                - |
                  echo "Starting MongoDB backup..."

                  # Wait for MongoDB to be ready
                  until mongo --host ${APP_NAME}-mongo:27017 --username admin --password $MONGODB_ADMIN_PASSWORD --authenticationDatabase admin --eval "db.runCommand('ping')" > /dev/null 2>&1; do
                    echo "Waiting for MongoDB to be available..."
                    sleep 10
                  done

                  echo "MongoDB is ready. Creating backup..."

                  # Create backup with all databases
                  mongodump --host ${APP_NAME}-mongo:27017 \
                           --username admin \
                           --password $MONGODB_ADMIN_PASSWORD \
                           --authenticationDatabase admin \
                           --out /backup/${BACKUP_NAME}

                  # Verify backup was created
                  if [ -d "/backup/${BACKUP_NAME}" ]; then
                    echo "✅ Backup created successfully at /backup/${BACKUP_NAME}"
                    echo "Backup contents:"
                    ls -la /backup/${BACKUP_NAME}/
                    echo "Backup size:"
                    du -sh /backup/${BACKUP_NAME}/
                  else
                    echo "❌ Backup failed!"
                    exit 1
                  fi

                  echo "Backup completed successfully!"
              env:
                - name: MONGODB_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: admin-password
                      name: ${APP_NAME}-mongo
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: ${APP_NAME}-mongo-backup-${BACKUP_NAME}
          restartPolicy: Never
      backoffLimit: 3
