kind: Template
apiVersion: v1
labels:
  app: ${APP_NAME}
parameters:
  - name: IMAGE_NAMESPACE
    description: The OpenShift namespace containing the server image stream
    required: true
  - name: APP_NAME
    description: App name that OpenShift objects will be prefixed with
    required: true
  - name: IMAGE_TAG
    description: ImageStream tag for build and deploy
    value: latest
    required: true
  - name: SERVER_PORT
    description: Port the server will be exposed on
    value: "8080"
    required: true
objects:
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${APP_NAME}-server
    spec:
      host: ""
      port:
        targetPort: web
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-server
        weight: 100
      wildcardPolicy: None
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-server
    spec:
      strategy:
        type: Rolling
        activeDeadlineSeconds: 21600
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APP_NAME}-server
            from:
              kind: ImageStreamTag
              name: ${APP_NAME}-server:${IMAGE_TAG}
              namespace: ${IMAGE_NAMESPACE}
          type: ImageChange
        - type: ConfigChange
      replicas: 1
      selector:
        name: ${APP_NAME}-server
      template:
        metadata:
          name: ${APP_NAME}-server
          labels:
            name: ${APP_NAME}-server
        spec:
          containers:
            - env:
                - name: POSTGRES_HOST
                  value: patroni-master-001 # ${APP_NAME}-patroni
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      key: db-name
                      name: patroni-001 # ${APP_NAME}-patroni
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      key: db-username
                      name: patroni-001 # ${APP_NAME}-patroni
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: db-password
                      name: patroni-001 # ${APP_NAME}-patroni
              name: ${APP_NAME}-server
              image: " "
              ports:
                - containerPort: "${{SERVER_PORT}}"
                  protocol: TCP
              resources:
                limits:
                  cpu: 500m
                  memory: 2Gi
                requests:
                  cpu: 100m
                  memory: 512Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
          dnsPolicy: ClusterFirst
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-server
    spec:
      ports:
        - name: web
          protocol: TCP
          port: ${{SERVER_PORT}}
          targetPort: ${{SERVER_PORT}}
      selector:
        name: ${APP_NAME}-server
      type: ClusterIP
      sessionAffinity: None
