# Promotion to test env.
# Trigger with tag push
# Connected with repo environment 'prod'
# TODO: Create more automated and user friendly workflow
name: OpenShift Deploy/Promotion to Production

on:
  push:
    tags:
      - prod

env:
  CLUSTER: https://api.silver.devops.gov.bc.ca:6443
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN_OCP4 }}
  PROJECT: hcap

jobs:
  promoteProd:
    name: OpenShift Promotion
    runs-on: ubuntu-latest
    concurrency: ci-promote-prod
    timeout-minutes: 6
    environment:
      name: prod
    env:
      OS_NAMESPACE_SUFFIX: prod
      SA_TOKEN: ${{ secrets.SA_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install OpenShift CLI
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest

      - name: Checking Deployment Config changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'openshift/**'
          base: 'refs/tags/prod'
      - name: Login to prod namespace
        if: ${{ env.SA_TOKEN }}
        run: |
          oc login --token="$SA_TOKEN" --server="$CLUSTER"
      - name: Test and Deploy
        if: steps.changes.outputs.src == 'true'
        run: |
          cd "$GITHUB_WORKSPACE"
          make server-config-test
          make cron-job-test
          make server-config
          make cron-job

      - name: Promote
        run: |
          cd "$GITHUB_WORKSPACE"
          oc login --token="$AUTH_TOKEN" --server="$CLUSTER"
          export OS_NAMESPACE_SUFFIX=${{ env.OS_NAMESPACE_SUFFIX }}
          make server-deploy

      - name: Microsoft Teams Deploy Card
        uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          environment: production
          card-layout-exit: complete
          timezone: America/Vancouver
          show-on-start: false
          show-on-exit: true
          show-on-failure: false
