name: Prod - Service Pod

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: 'Image tag'
        required: true
        default: dev
      CONFIG:
        description: 'The service configuration string'
        required: true

env:
  CLUSTER: https://api.silver.devops.gov.bc.ca:6443
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN_OCP4 }}
  SA_TOKEN: ${{ secrets.SA_TOKEN_CONFIG }}
  PROJECT: hcap
  SERVICE_CONFIG_INPUT: ${{ github.event.inputs.CONFIG }}
jobs:
  service-exe:
    name: service-exe
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Execute Service Pod
        env:
          OS_NAMESPACE_SUFFIX: prod
          SA_TOKEN: ${{ secrets.SA_TOKEN }}
        run: |
          oc login --token="$SA_TOKEN" --server="$CLUSTER"
          cd "$GITHUB_WORKSPACE"
          make service-pod tag=${{ github.event.inputs.IMAGE_TAG }}
