name: Slack Notification Demo
on:
  push:
    branches: [slack]

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
          SLACK_USERNAME: Deploy-Updates
          SLACK_TITLE: 'Tagged xyz'
          SLACK_MESSAGE: 'Post Content :rocket:'
