name: Test Env specific changes
on: 
 workflow_dispatch:
   
jobs: 
  test:
    name: Test environment specific work flow
    runs-on: ubuntu-20.04
    environment:
      name: dev
    steps:
      - name: Just Echo
        run: echo "Hello world"